name: CI/CD Pipeline for Medusa on ECS Fargate Spot

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Create an Amazon ECR repository (if it doesn't already exist)
      - name: Create ECR Repository
        run: |
          aws ecr describe-repositories --repository-names jaswanth-medusa || \
          aws ecr create-repository \
            --repository-name jaswanth-medusa \
            --image-scanning-configuration scanOnPush=true \
            --region us-east-1

      # Log in to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t jaswanth-medusa:latest .
          docker tag jaswanth-medusa:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/jaswanth-medusa:latest

      # Push the Docker image to ECR
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/jaswanth-medusa:latest

      # Deploy to ECS Fargate Spot
      - name: Deploy to ECS Fargate Spot
        run: |
          aws ecs update-service \
            --cluster medusa-ecs-cluster \
            --service medusa-ecs-service \
            --force-new-deployment
